# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vintent_pb2 as vintent__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Analyze = channel.stream_unary(
        '/action_module.Greeter/Analyze',
        request_serializer=vintent__pb2.MsgRequest.SerializeToString,
        response_deserializer=vintent__pb2.MsgReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def Analyze(self, request_iterator, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Analyze': grpc.stream_unary_rpc_method_handler(
          servicer.Analyze,
          request_deserializer=vintent__pb2.MsgRequest.FromString,
          response_serializer=vintent__pb2.MsgReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'action_module.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
